<?php
$this->title = "Novelty Items";
$this->headTitle($this->title);
?>
<h2>Novelty Items List:</h2>
<p><a href="<?php echo $this->url(array('controller'=>'Noveltyitems','action'=>'index'));?>">Add New Novelty Item</a></p>

<table border="1">
<tr>
<th>Name</th>
<th>Title</th>
<th>Description</th>
<th>Price</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->noveltyitems as $nitem) : ?>
<tr>
<td><?php echo $this->escape($nitem->Name);?></td>
<td><?php echo $this->escape($nitem->Title);?></td>
<td><?php echo $this->escape($nitem->Description);?></td>
<td><?php echo $this->escape($nitem->Price);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Noveltyitems', 'action'=>'edit', 'noveltyid'=>$nitem->NoveltyId));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'Noveltyitems', 'action'=>'delete', 'noveltyid'=>$nitem->NoveltyId));?>">Delete</a>

</td>
</tr>
<?php endforeach; ?>
</table>
