<?php

$this->title = "My School";
$this->headTitle($this->title);
?>
<h2><?php
 
$userDetails = new Zend_Session_Namespace('userDetails');
$dd= $this->dictionary->getDictionary('Registered User List', $userDetails->lang); 

echo $dd->Value;

?>:</h2>
<p><a href="<?php echo $this->url(array('controller'=>'Projects','action'=>'index'));?>">Add New Project</a></p>

<table border="1">
<tr>
<th>Project Name</th>
<th>User Registration</th>
<th>Description</th>
<th>Last Name</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->projects as $sreg) : ?>
<tr>
<td><?php echo $this->escape($sreg->ProjectName);?></td>
<td><?php echo $this->escape($sreg->UserRegistrationId);?></td>
<td><?php echo $this->escape($sreg->Description);?></td>
<td><?php echo $this->escape($sreg->Goal_Investment);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Projects', 'action'=>'edit', 'projectid'=>$sreg->ProjectId));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'Projects', 'action'=>'delete', 'projectid'=>$sreg->ProjectId));?>" onclick="confirm('do you want to delete it')">Delete</a>

</td>
</tr>
<?php endforeach; ?>
</table>


