<div style="padding: 4px;">
    <table style="width: 50%;">
        <tbody>
            <tr>
                <td>Username:</td>
                <td><?=$this->element->getElement('UserId'); ?></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><?=$this->element->getElement('Password'); ?></td>
            </tr>
        </tbody>
    </table>
    <?=$this->element->getElement('submit'); ?>
</div>