<?php

$this->title = "My School";
$this->headTitle($this->title);
?>
<h2><?php
 
$userDetails = new Zend_Session_Namespace('userDetails');
$dd= $this->dictionary->getDictionary('Registered User List', $userDetails->lang); 

echo $dd->Value;

?>:</h2>
<p><a href="<?php echo $this->url(array('controller'=>'Userregistration','action'=>'index'));?>">Add New User</a></p>

<table border="1">
<tr>
<th>Userid</th>
<th>Password</th>
<th>First Name</th>
<th>Last Name</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->userregistration as $sreg) : ?>
<tr>
<td><?php echo $this->escape($sreg->UserId);?></td>
<td><?php echo $this->escape($sreg->Password);?></td>
<td><?php echo $this->escape($sreg->FirstName);?></td>
<td><?php echo $this->escape($sreg->LastName);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Userregistration', 'action'=>'edit', 'registerid'=>$sreg->RegisterID));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'Userregistration', 'action'=>'delete', 'registerid'=>$sreg->RegisterID));?>">Delete</a>

</td>
</tr>
<?php endforeach; ?>
</table>


