<table width="100%" border="0" cellpadding="4">
  <tr>
    <td width="17%">UserId</td>
    <td width="73%"><?=$this->element->getElement('UserId'); ?>&nbsp;</td>
    <td width="10%">&nbsp;</td>
  </tr>
  <tr>
    <td>Password</td>
    <td><?=$this->element->getElement('Password'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Email</td>
    <td><?=$this->element->getElement('Email'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Phone Office</td>
    <td><?=$this->element->getElement('PhoneOffice'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Phone Home</td>
    <td><?=$this->element->getElement('PhoneHome'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Mobile</td>
    <td><?=$this->element->getElement('Mobile'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Privillages</td>
    <td><?=$this->element->getElement('Privillages'); ?>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><?=$this->element->getElement('submit'); ?>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>

