<?php
$projectdetails= $this->schoolprojects;
$pimg=$projectdetails['ThankyouImagePath'];
$totalinvestment = $this->totalinvestment;

//echo $this->baseUrl('images/logo.jpg');


//echo $pimg;

?>
<h2>Project: <?php echo $projectdetails['ProjectName'] ?> Details</h2>

<table width="100%" border="1" cellpadding="3">
  <tr>
    <td width="36%"><table width="100%" border="1" cellpadding="5" cellspacing="0">
      <tr>
        <td width="39%">Project Name</td>
        <td width="61%"><?php echo $projectdetails['ProjectName'] ?>&nbsp;</td>
      </tr>
      <tr>
        <td>Description</td>
        <td><?php echo $projectdetails['Description'] ?>&nbsp;</td>
      </tr>
      <tr>
        <td>Goal Investment</td>
        <td><?php echo $projectdetails['Goal_Investment'] ?>&nbsp;</td>
      </tr>
      <tr>
        <td>Investment Collected</td>
        <td><?php echo $this->totalinvestment ?>&nbsp;</td>
      </tr>
    </table></td>
    <td width="64%" align="center" valign="top"><img src="<?php echo $this->baseUrl('projectsupload/').$pimg ?>" width="80px" height="80px"  />&nbsp;</td>
  </tr>
</table>

