<?php echo $this->doctype() ; ?>
<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
    <?php //echo $this->headTitle("abc"); ?>
    <? $this->headLink()->prependStylesheet($this->baseUrl('css/global.css')) ?> 
    <? $this->headLink()->appendStylesheet('/css/iefix.css','screen','lt IE 7') ?>     
    <?= $this->cssHelper() ?>    
    <? $this->headScript()->appendFile('/js/jquery-1.3.2.min.js') ?> 
    <? $this->headScript()->appendFile('/js/global.js') ?> 
     
    <? $this->javascriptHelper() ?> 
    <?= $this->headScript() ?> 
    
</head>
<body>

<div class="header">
<h1>My Website</h1>
<ul>
<li><a href="<?php echo $this->url(array('controller'=>'Schoolregistration', 'action'=>'list', 'registerid'=>$sreg->RegisterID),null,true);?>" > Home</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'Projects', 'action'=>'list'),null,true);?>" > Projects</a></li>
<li><a href="#" > About Us</a></li>
<li><a href="#" > Contact Us</a></li>


</ul>


</div>
<div class="content">
<div class="rightcontent">this is right content</div>

<?php  echo $this->layout()->content;

?>
</div>


<div class="footer"></div>
</body>