<?php

$this->title = "My School";
$this->headTitle($this->title);
?>
<h2><?php
 
$userDetails = new Zend_Session_Namespace('userDetails');
$dd= $this->dictionary->getDictionary('Project Images List', $userDetails->lang); 

//echo $dd->Value;
echo "Project Images List";

?>:</h2>
<p><a href="<?php echo $this->url(array('controller'=>'Projectimages','action'=>'index'));?>">Add New User</a></p>

<table border="1">
<tr>
<th>Projectid</th>
<th>Image Path</th>
<th>Create Date</th>
<th></th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->projectimages as $sreg) : ?>
<tr>
<td><?php echo $this->escape($sreg->ProjectId);?></td>
<td><?php echo $this->escape($sreg->ImagePath);?></td>
<td><?php echo $this->escape($sreg->CreateDate);?></td>
<td></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Projectimages', 'action'=>'edit', 'projectimagesid'=>$sreg->ProjectImageId));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'Projectimages', 'action'=>'delete', 'projectimagesid'=>$sreg->ProjectImageId));?>">Delete</a>

</td>
</tr>
<?php endforeach; ?>
</table>


