<?php
$this->title = "My School";
$this->headTitle($this->title);
?>
<h2>Registered School List:</h2>
<p><a href="<?php echo $this->url(array('controller'=>'Schoolsocialmedia','action'=>'index'));?>">Add New School</a></p>

<table border="1">
<tr>
<th>Userid</th>
<th>Password</th>
<th>First Name</th>
<th>Last Name</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->schoolregistration as $sreg) : ?>
<tr>
<td><?php echo $this->escape($sreg->UserId);?></td>
<td><?php echo $this->escape($sreg->Password);?></td>
<td><?php echo $this->escape($sreg->ContactFirstName);?></td>
<td><?php echo $this->escape($sreg->ContactLastName);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Schoolsocialmedia', 'action'=>'edit', 'registrationid'=>$sreg->RegistrationId));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'Schoolsocialmedia', 'action'=>'delete', 'registrationid'=>$sreg->RegistrationId));?>">Delete</a>

</td>
</tr>
<?php endforeach; ?>
</table>
