


<div class="banner_border"></div>
       
    <section class="banner_wrapper">
      <div id="sliding_wrapper"> 
	  
		<div class="quake-slider">
                <div class="quake-slider-images">
                    <div>
						<a href="javascript:"> <img src="images/sliding-banner1.jpg" alt=""></a>
						<div class="captionWrapper">
							<p>asdfasdf</p>
						</div>	
					</div>	
                    <a href="javascript:"> <img src="images/sliding-banner2.jpg" alt=""> </a> 
                    <a href="javascript:"> <img src="images/sliding-banner3.jpg" alt=""> </a>
                   
                </div>
        
		    </div>
	    </div>
	 
      
	<div class="banner_menu"> 
		<div class="staff_pic"> 
			<a href="">
				<img src="images/staff.jpg" alt="">
				<div class="small_banner_span">Staff</div>
			</a> 
		</div>
		<div class="popular"> 
			<a href=""> 
			<img src="images/popular.jpg" alt="">
		    <div class="small_banner_span">Most Popular</div>
			</a> 
		</div>
	</div>	
	
	<div style="border-bottom:none" class="banner_menu"> 
		<div class="learn"> 
			<a href=""> 
				<img src="images/learn.jpg" alt="">
				<div class="small_banner_span">Learn</div>
			</a> 
		</div>
		<div class="past_succ"> 
			<a href=""> 
				<img src="images/past_succ.jpg" alt="">
				<div class="small_banner_span">Past Success</div>
			</a> 
		</div>
		<div class="goal"> 
			<a href=""> 
				<img src="images/goal.jpg" alt="">
				<div class="small_banner_span">Near Goal</div>
			</a> 
		</div>
	</div>
	
    </section>
     <div class="clear"></div>
	
	 <div class="banner_border"></div>
  </header>
  <!--container -->
  <section id="content-container" class="clear">
    <div id="center_wrap">
      <!--leading Cause -->
      <div class="leading_cause">
        <h1>Leading Cause</h1>
        <div id="days_left_wrapper">
          <div class="days_left">15</div>
          <span>Days Left -</span> <a href="#" class="navy tt-button"> Join the Competition </a> </div>
        <div class="clear"></div>
        <div class="leading_cause_wrapper">
          <div class="one_fourth">
            <div class="img_frame_full-fourth">
              <div class="thumb_hover_wrapper">
                <div class="thumb_hover"></div>
                <div class="thumb_context">
                  <h2>Cause Name</h2>
                  <h3>Amount Raised: $2,000</h3>
                  <h4>15 Days Left</h4>
                </div>
              </div>
              <img src="images/leading1.jpg" alt=""> </div>
            <div class="cause_bg"></div>
          </div>
          <div class="one_fourth">
            <div class="img_frame_full-fourth">
              <div class="thumb_hover_wrapper">
                <div class="thumb_hover"></div>
                <div class="thumb_context">
                  <h2>Cause Name</h2>
                  <h3>Amount Raised: $2,000</h3>
                  <h4>15 Days Left</h4>
                </div>
              </div>
              <img src="images/leading2.jpg" alt=""> </div>
            <div class="cause_bg"></div>
          </div>
          <div class="one_fourth">
            <div class="img_frame_full-fourth">
              <div class="thumb_hover_wrapper">
                <div class="thumb_hover"></div>
                <div class="thumb_context">
                  <h2>Cause Name</h2>
                  <h3>Amount Raised: $2,000</h3>
                  <h4>15 Days Left</h4>
                </div>
              </div>
              <img src="images/leading3.jpg" alt=""> </div>
            <div class="cause_bg"></div>
          </div>
          <div class="one_fourth">
            <div class="img_frame_full-fourth">
              <div class="thumb_hover_wrapper">
                <div class="thumb_hover"></div>
                <div class="thumb_context">
                  <h2>Cause Name</h2>
                  <h3>Amount Raised: $2,000</h3>
                  <h4>15 Days Left</h4>
                </div>
              </div>
              <img src="images/leading4.jpg" alt=""> </div>
            <div class="cause_bg"></div>
          </div>
        </div>
      </div>
      <div class="clear"></div>
      <div class="mov_advocates_wrapper">
        <h1>Movement Advocates</h1>
        <div class="frnd_list">
          <ul>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
            <li><a><img src="images/leading2.jpg" alt=""></a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>